from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(958, 740)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backButton = QtWidgets.QPushButton(parent=Form)
        self.backButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/back_button.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mainLabel = QtWidgets.QLabel(parent=Form)
        self.mainLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainLabel.setObjectName("mainLabel")
        self.horizontalLayout.addWidget(self.mainLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.nameLabel = QtWidgets.QLabel(parent=Form)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.nameField = QtWidgets.QLineEdit(parent=Form)
        self.nameField.setObjectName("nameField")
        self.verticalLayout.addWidget(self.nameField)
        self.emailLabel = QtWidgets.QLabel(parent=Form)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout.addWidget(self.emailLabel)
        self.emailField = QtWidgets.QLineEdit(parent=Form)
        self.emailField.setObjectName("emailField")
        self.verticalLayout.addWidget(self.emailField)
        self.passLabel = QtWidgets.QLabel(parent=Form)
        self.passLabel.setObjectName("passLabel")
        self.verticalLayout.addWidget(self.passLabel)
        self.passField = QtWidgets.QLineEdit(parent=Form)
        self.passField.setObjectName("passField")
        self.verticalLayout.addWidget(self.passField)
        self.cPassLabel = QtWidgets.QLabel(parent=Form)
        self.cPassLabel.setObjectName("cPassLabel")
        self.verticalLayout.addWidget(self.cPassLabel)
        self.cPassField = QtWidgets.QLineEdit(parent=Form)
        self.cPassField.setObjectName("cPassField")
        self.verticalLayout.addWidget(self.cPassField)
        self.createAccButton = QtWidgets.QPushButton(parent=Form)
        self.createAccButton.setObjectName("createAccButton")
        self.verticalLayout.addWidget(self.createAccButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)




        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mainLabel.setText(_translate("Form", "UNI TIME"))
        self.label_4.setText(_translate("Form", "Sign Up"))
        self.nameLabel.setText(_translate("Form", "Full Name"))
        self.emailLabel.setText(_translate("Form", "Email"))
        self.passLabel.setText(_translate("Form", "Password"))
        self.cPassLabel.setText(_translate("Form", "Confirm password"))
        self.createAccButton.setText(_translate("Form", "Create Account"))

def create_account_page(self):
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.ui = ui
    return widget