from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(955, 1021)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.courseLabel = QtWidgets.QLabel(parent=Form)
        self.courseLabel.setObjectName("courseLabel")
        self.verticalLayout.addWidget(self.courseLabel)
        self.courseField = QtWidgets.QLineEdit(parent=Form)
        self.courseField.setObjectName("courseField")
        self.verticalLayout.addWidget(self.courseField)
        self.AssignmentLabel = QtWidgets.QLabel(parent=Form)
        self.AssignmentLabel.setObjectName("AssignmentLabel")
        self.verticalLayout.addWidget(self.AssignmentLabel)
        self.AssignmentField = QtWidgets.QLineEdit(parent=Form)
        self.AssignmentField.setObjectName("AssignmentField")
        self.verticalLayout.addWidget(self.AssignmentField)
        self.DescriptionLabel = QtWidgets.QLabel(parent=Form)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.verticalLayout.addWidget(self.DescriptionLabel)
        self.DescriptionField = QtWidgets.QLineEdit(parent=Form)
        self.DescriptionField.setObjectName("DescriptionField")
        self.verticalLayout.addWidget(self.DescriptionField)
        self.DueLabel = QtWidgets.QLabel(parent=Form)
        self.DueLabel.setObjectName("DueLabel")
        self.verticalLayout.addWidget(self.DueLabel)
        self.dueField = QtWidgets.QDateEdit(parent=Form)
        self.dueField.setObjectName("dueField")
        self.verticalLayout.addWidget(self.dueField)
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 4, 11, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.taskTable = QtWidgets.QTableWidget(parent=Form)
        self.taskTable.setMinimumSize(QtCore.QSize(600, 0))
        self.taskTable.setMaximumSize(QtCore.QSize(600, 16777215))
        self.taskTable.setObjectName("taskTable")
        self.taskTable.setColumnCount(5)
        self.taskTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.taskTable.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.taskTable, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.deleteButton = QtWidgets.QPushButton(parent=Form)
        self.deleteButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uni_time/Assets/Delete Vector Icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.logOutButton = QtWidgets.QPushButton(parent=Form)
        self.logOutButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("uni_time/Assets/Log Out 01 Icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logOutButton.setIcon(icon1)
        self.logOutButton.setObjectName("logOutButton")
        self.horizontalLayout.addWidget(self.logOutButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 11, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.courseLabel.setText(_translate("Form", "Course Name:"))
        self.AssignmentLabel.setText(_translate("Form", "Assignmet Name"))
        self.DescriptionLabel.setText(_translate("Form", "Description"))
        self.DueLabel.setText(_translate("Form", "Due Date"))
        self.addButton.setText(_translate("Form", "Add a task"))
        self.label.setText(_translate("Form", "UNI TIME"))
        item = self.taskTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Course"))
        item = self.taskTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Assignment"))
        item = self.taskTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Description"))
        item = self.taskTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Due Date"))

def job_applications():
    widget = QtWidgets.QWidget()
    ui = Ui_Form
    ui.setupUi(widget)
    widget.ui = ui
    return widget
