from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1007, 1021)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.jIdLabel = QtWidgets.QLabel(parent=Form)
        self.jIdLabel.setObjectName("jIdLabel")
        self.verticalLayout.addWidget(self.jIdLabel)
        self.jobIdField = QtWidgets.QLineEdit(parent=Form)
        self.jobIdField.setText("")
        self.jobIdField.setObjectName("jobIdField")
        self.verticalLayout.addWidget(self.jobIdField)
        self.jTitleLabel = QtWidgets.QLabel(parent=Form)
        self.jTitleLabel.setObjectName("jTitleLabel")
        self.verticalLayout.addWidget(self.jTitleLabel)
        self.JTitleField = QtWidgets.QLineEdit(parent=Form)
        self.JTitleField.setObjectName("JTitleField")
        self.verticalLayout.addWidget(self.JTitleField)
        self.DescriptionLabel = QtWidgets.QLabel(parent=Form)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.verticalLayout.addWidget(self.DescriptionLabel)
        self.CField = QtWidgets.QLineEdit(parent=Form)
        self.CField.setObjectName("CField")
        self.verticalLayout.addWidget(self.CField)
        self.aDateLabel = QtWidgets.QLabel(parent=Form)
        self.aDateLabel.setObjectName("aDateLabel")
        self.verticalLayout.addWidget(self.aDateLabel)
        self.aDateField = QtWidgets.QDateEdit(parent=Form)
        self.aDateField.setObjectName("aDateField")
        self.verticalLayout.addWidget(self.aDateField)
        self.notesLabel = QtWidgets.QLabel(parent=Form)
        self.notesLabel.setObjectName("notesLabel")
        self.verticalLayout.addWidget(self.notesLabel)
        self.notesField = QtWidgets.QLineEdit(parent=Form)
        self.notesField.setObjectName("notesField")
        self.verticalLayout.addWidget(self.notesField)
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 3, 14, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/dlt_icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.docbtn = QtWidgets.QPushButton(parent=Form)
        self.docbtn.setObjectName("docbtn")
        self.horizontalLayout.addWidget(self.docbtn, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 14, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 7, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.jobTable = QtWidgets.QTableWidget(parent=Form)
        self.jobTable.setMinimumSize(QtCore.QSize(700, 0))
        self.jobTable.setMaximumSize(QtCore.QSize(600, 16777215))
        self.jobTable.setObjectName("jobTable")
        self.jobTable.setColumnCount(7)
        self.jobTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.jobTable.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_5.addWidget(self.jobTable)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.backbtn = QtWidgets.QPushButton(parent=Form)
        self.backbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/back_button.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backbtn.setIcon(icon1)
        self.backbtn.setObjectName("backbtn")
        self.gridLayout.addWidget(self.backbtn, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 6, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.jIdLabel.setText(_translate("Form", "Job ID"))
        self.jTitleLabel.setText(_translate("Form", "Job Title"))
        self.DescriptionLabel.setText(_translate("Form", "Company"))
        self.aDateLabel.setText(_translate("Form", "Applied Date"))
        self.notesLabel.setText(_translate("Form", "Notes"))
        self.addButton.setText(_translate("Form", "Add"))
        self.docbtn.setText(_translate("Form", "Export"))
        item = self.jobTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "JobID"))
        item = self.jobTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Job Title"))
        item = self.jobTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Company"))
        item = self.jobTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Applied date"))
        item = self.jobTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Notes"))
        item = self.jobTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Status"))
        self.label.setText(_translate("Form", "UNI TIME"))




def job_applications(self):
    widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(widget)
    widget.ui = ui
    return widget
